# Generated by Django 3.2.11 on 2022-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='completecount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
