# Generated by Django 3.2.11 on 2022-04-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0001_initial'),
        ('accounts2', '0002_alter_profile_completecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='common_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wm.commonsubject'),
        ),
    ]
