# Generated by Django 3.2.11 on 2022-04-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0002_remove_profile_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subject_of_memo',
            new_name='subject',
        ),
    ]
