# Generated by Django 3.2.11 on 2022-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0003_rename_subject_of_memo_profile_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
